//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Messages" +
        "")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FatherUniqueIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlainBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Recipient> RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.MessageSettings SettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UniqueIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FatherUniqueIdentifier {
            get {
                return this.FatherUniqueIdentifierField;
            }
            set {
                if ((this.FatherUniqueIdentifierField.Equals(value) != true)) {
                    this.FatherUniqueIdentifierField = value;
                    this.RaisePropertyChanged("FatherUniqueIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLanguage {
            get {
                return this.IdLanguageField;
            }
            set {
                if ((this.IdLanguageField.Equals(value) != true)) {
                    this.IdLanguageField = value;
                    this.RaisePropertyChanged("IdLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlainBody {
            get {
                return this.PlainBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.PlainBodyField, value) != true)) {
                    this.PlainBodyField = value;
                    this.RaisePropertyChanged("PlainBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Recipient> Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.MessageSettings Settings {
            get {
                return this.SettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsField, value) != true)) {
                    this.SettingsField = value;
                    this.RaisePropertyChanged("Settings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UniqueIdentifier {
            get {
                return this.UniqueIdentifierField;
            }
            set {
                if ((this.UniqueIdentifierField.Equals(value) != true)) {
                    this.UniqueIdentifierField = value;
                    this.RaisePropertyChanged("UniqueIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageSettings", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Messages" +
        "")]
    [System.SerializableAttribute()]
    public partial class MessageSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CopyToSenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdSkinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotifyToSenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SubjectPrefixType PrefixTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SenderUserType SenderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Signature SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CopyToSender {
            get {
                return this.CopyToSenderField;
            }
            set {
                if ((this.CopyToSenderField.Equals(value) != true)) {
                    this.CopyToSenderField = value;
                    this.RaisePropertyChanged("CopyToSender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdSkin {
            get {
                return this.IdSkinField;
            }
            set {
                if ((this.IdSkinField.Equals(value) != true)) {
                    this.IdSkinField = value;
                    this.RaisePropertyChanged("IdSkin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBodyHtml {
            get {
                return this.IsBodyHtmlField;
            }
            set {
                if ((this.IsBodyHtmlField.Equals(value) != true)) {
                    this.IsBodyHtmlField = value;
                    this.RaisePropertyChanged("IsBodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotifyToSender {
            get {
                return this.NotifyToSenderField;
            }
            set {
                if ((this.NotifyToSenderField.Equals(value) != true)) {
                    this.NotifyToSenderField = value;
                    this.RaisePropertyChanged("NotifyToSender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SubjectPrefixType PrefixType {
            get {
                return this.PrefixTypeField;
            }
            set {
                if ((this.PrefixTypeField.Equals(value) != true)) {
                    this.PrefixTypeField = value;
                    this.RaisePropertyChanged("PrefixType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SenderUserType SenderType {
            get {
                return this.SenderTypeField;
            }
            set {
                if ((this.SenderTypeField.Equals(value) != true)) {
                    this.SenderTypeField = value;
                    this.RaisePropertyChanged("SenderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Signature Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((this.SignatureField.Equals(value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Messages" +
        "")]
    [System.SerializableAttribute()]
    public partial class Recipient : lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.UserMailAddress {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCommunityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdModuleObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdModuleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdUserModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.RecipientStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.RecipientType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCommunity {
            get {
                return this.IdCommunityField;
            }
            set {
                if ((this.IdCommunityField.Equals(value) != true)) {
                    this.IdCommunityField = value;
                    this.RaisePropertyChanged("IdCommunity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLanguage {
            get {
                return this.IdLanguageField;
            }
            set {
                if ((this.IdLanguageField.Equals(value) != true)) {
                    this.IdLanguageField = value;
                    this.RaisePropertyChanged("IdLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdModuleObject {
            get {
                return this.IdModuleObjectField;
            }
            set {
                if ((this.IdModuleObjectField.Equals(value) != true)) {
                    this.IdModuleObjectField = value;
                    this.RaisePropertyChanged("IdModuleObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModuleType {
            get {
                return this.IdModuleTypeField;
            }
            set {
                if ((this.IdModuleTypeField.Equals(value) != true)) {
                    this.IdModuleTypeField = value;
                    this.RaisePropertyChanged("IdModuleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerson {
            get {
                return this.IdPersonField;
            }
            set {
                if ((this.IdPersonField.Equals(value) != true)) {
                    this.IdPersonField = value;
                    this.RaisePropertyChanged("IdPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRole {
            get {
                return this.IdRoleField;
            }
            set {
                if ((this.IdRoleField.Equals(value) != true)) {
                    this.IdRoleField = value;
                    this.RaisePropertyChanged("IdRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdUserModule {
            get {
                return this.IdUserModuleField;
            }
            set {
                if ((this.IdUserModuleField.Equals(value) != true)) {
                    this.IdUserModuleField = value;
                    this.RaisePropertyChanged("IdUserModule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.RecipientStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.RecipientType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMailAddress", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Messages" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Recipient))]
    public partial class UserMailAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipientStatus", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain")]
    public enum RecipientStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipientType", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain")]
    public enum RecipientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        To = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BCC = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectPrefixType", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain")]
    public enum SubjectPrefixType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemConfiguration = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenderUserType", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain")]
    public enum SenderUserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedUser = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherUser = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Signature", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain")]
    public enum Signature : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromConfigurationSettings = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromTemplate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromSkin = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromField = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromNoReplySettings = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmtpServiceConfig", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Configur" +
        "ations")]
    [System.SerializableAttribute()]
    public partial class SmtpServiceConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SmtpAuthenticationConfig AuthenticationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefaultHTMLmodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SenderSettings> DefaultSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.UserMailAddress ErrorSenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RelayAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SendMailErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.UserMailAddress SystemSenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SmtpAuthenticationConfig Authentication {
            get {
                return this.AuthenticationField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationField, value) != true)) {
                    this.AuthenticationField = value;
                    this.RaisePropertyChanged("Authentication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DefaultHTMLmode {
            get {
                return this.DefaultHTMLmodeField;
            }
            set {
                if ((this.DefaultHTMLmodeField.Equals(value) != true)) {
                    this.DefaultHTMLmodeField = value;
                    this.RaisePropertyChanged("DefaultHTMLmode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SenderSettings> DefaultSettings {
            get {
                return this.DefaultSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultSettingsField, value) != true)) {
                    this.DefaultSettingsField = value;
                    this.RaisePropertyChanged("DefaultSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.UserMailAddress ErrorSender {
            get {
                return this.ErrorSenderField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSenderField, value) != true)) {
                    this.ErrorSenderField = value;
                    this.RaisePropertyChanged("ErrorSender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRecipients {
            get {
                return this.MaxRecipientsField;
            }
            set {
                if ((this.MaxRecipientsField.Equals(value) != true)) {
                    this.MaxRecipientsField = value;
                    this.RaisePropertyChanged("MaxRecipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RelayAllowed {
            get {
                return this.RelayAllowedField;
            }
            set {
                if ((this.RelayAllowedField.Equals(value) != true)) {
                    this.RelayAllowedField = value;
                    this.RaisePropertyChanged("RelayAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendMailError {
            get {
                return this.SendMailErrorField;
            }
            set {
                if ((this.SendMailErrorField.Equals(value) != true)) {
                    this.SendMailErrorField = value;
                    this.RaisePropertyChanged("SendMailError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.UserMailAddress SystemSender {
            get {
                return this.SystemSenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemSenderField, value) != true)) {
                    this.SystemSenderField = value;
                    this.RaisePropertyChanged("SystemSender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmtpAuthenticationConfig", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Configur" +
        "ations")]
    [System.SerializableAttribute()]
    public partial class SmtpAuthenticationConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnableSslField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseDefaultCredentialsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountPassword {
            get {
                return this.AccountPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPasswordField, value) != true)) {
                    this.AccountPasswordField = value;
                    this.RaisePropertyChanged("AccountPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnableSsl {
            get {
                return this.EnableSslField;
            }
            set {
                if ((this.EnableSslField.Equals(value) != true)) {
                    this.EnableSslField = value;
                    this.RaisePropertyChanged("EnableSsl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseDefaultCredentials {
            get {
                return this.UseDefaultCredentialsField;
            }
            set {
                if ((this.UseDefaultCredentialsField.Equals(value) != true)) {
                    this.UseDefaultCredentialsField = value;
                    this.RaisePropertyChanged("UseDefaultCredentials");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenderSettings", Namespace="http://schemas.datacontract.org/2004/07/lm.Comol.Core.MailCommons.Domain.Configur" +
        "ations")]
    [System.SerializableAttribute()]
    public partial class SenderSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMultiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoReplySignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectForSenderCopyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectPrefixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeLanguage {
            get {
                return this.CodeLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeLanguageField, value) != true)) {
                    this.CodeLanguageField = value;
                    this.RaisePropertyChanged("CodeLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLanguage {
            get {
                return this.IdLanguageField;
            }
            set {
                if ((this.IdLanguageField.Equals(value) != true)) {
                    this.IdLanguageField = value;
                    this.RaisePropertyChanged("IdLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMulti {
            get {
                return this.IsMultiField;
            }
            set {
                if ((this.IsMultiField.Equals(value) != true)) {
                    this.IsMultiField = value;
                    this.RaisePropertyChanged("IsMulti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoReplySignature {
            get {
                return this.NoReplySignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.NoReplySignatureField, value) != true)) {
                    this.NoReplySignatureField = value;
                    this.RaisePropertyChanged("NoReplySignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectForSenderCopy {
            get {
                return this.SubjectForSenderCopyField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectForSenderCopyField, value) != true)) {
                    this.SubjectForSenderCopyField = value;
                    this.RaisePropertyChanged("SubjectForSenderCopy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectPrefix {
            get {
                return this.SubjectPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectPrefixField, value) != true)) {
                    this.SubjectPrefixField = value;
                    this.RaisePropertyChanged("SubjectPrefix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvMailSender.iServiceMailSender")]
    public interface iServiceMailSender {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailMessage")]
        void SendMailMessage(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailMessage")]
        System.Threading.Tasks.Task SendMailMessageAsync(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailWithSettings")]
        void SendMailWithSettings(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SmtpServiceConfig config, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailWithSettings")]
        System.Threading.Tasks.Task SendMailWithSettingsAsync(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SmtpServiceConfig config, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailFromModuleNotification")]
        void SendMailFromModuleNotification(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.dtoModuleNotificationMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailFromModuleNotification")]
        System.Threading.Tasks.Task SendMailFromModuleNotificationAsync(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.dtoModuleNotificationMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailFromGroupNotification")]
        void SendMailFromGroupNotification(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.GroupMessages message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailFromGroupNotification")]
        System.Threading.Tasks.Task SendMailFromGroupNotificationAsync(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.GroupMessages message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailMessagesFromTemplate")]
        void SendMailMessagesFromTemplate(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.MessageSettings mailSettings, System.Collections.Generic.List<lm.Comol.Core.Mail.Messages.dtoMailTranslatedMessage> messages, lm.Comol.Core.Mail.Messages.dtoBaseMailTemplate template, lm.Comol.Core.DomainModel.ModuleObject obj, int idCommunity, bool isPortal, System.Collections.Generic.List<string> attachments, string attachmentPath, bool saveMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iServiceMailSender/SendMailMessagesFromTemplate")]
        System.Threading.Tasks.Task SendMailMessagesFromTemplateAsync(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.MessageSettings mailSettings, System.Collections.Generic.List<lm.Comol.Core.Mail.Messages.dtoMailTranslatedMessage> messages, lm.Comol.Core.Mail.Messages.dtoBaseMailTemplate template, lm.Comol.Core.DomainModel.ModuleObject obj, int idCommunity, bool isPortal, System.Collections.Generic.List<string> attachments, string attachmentPath, bool saveMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iServiceMailSenderChannel : lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.iServiceMailSender, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iServiceMailSenderClient : System.ServiceModel.ClientBase<lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.iServiceMailSender>, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.iServiceMailSender {
        
        public iServiceMailSenderClient() {
        }
        
        public iServiceMailSenderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iServiceMailSenderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iServiceMailSenderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iServiceMailSenderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMailMessage(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath) {
            base.Channel.SendMailMessage(istanceIdentifier, idUser, idCommunity, moduleCode, message, attachmentPath, saveMessage, attachmentSavedPath);
        }
        
        public System.Threading.Tasks.Task SendMailMessageAsync(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath) {
            return base.Channel.SendMailMessageAsync(istanceIdentifier, idUser, idCommunity, moduleCode, message, attachmentPath, saveMessage, attachmentSavedPath);
        }
        
        public void SendMailWithSettings(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SmtpServiceConfig config, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath) {
            base.Channel.SendMailWithSettings(istanceIdentifier, idUser, idCommunity, moduleCode, config, message, attachmentPath, saveMessage, attachmentSavedPath);
        }
        
        public System.Threading.Tasks.Task SendMailWithSettingsAsync(string istanceIdentifier, int idUser, int idCommunity, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.SmtpServiceConfig config, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.Message message, string attachmentPath, bool saveMessage, string attachmentSavedPath) {
            return base.Channel.SendMailWithSettingsAsync(istanceIdentifier, idUser, idCommunity, moduleCode, config, message, attachmentPath, saveMessage, attachmentSavedPath);
        }
        
        public void SendMailFromModuleNotification(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.dtoModuleNotificationMessage message) {
            base.Channel.SendMailFromModuleNotification(istanceIdentifier, idUser, moduleCode, message);
        }
        
        public System.Threading.Tasks.Task SendMailFromModuleNotificationAsync(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.dtoModuleNotificationMessage message) {
            return base.Channel.SendMailFromModuleNotificationAsync(istanceIdentifier, idUser, moduleCode, message);
        }
        
        public void SendMailFromGroupNotification(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.GroupMessages message) {
            base.Channel.SendMailFromGroupNotification(istanceIdentifier, idUser, moduleCode, message);
        }
        
        public System.Threading.Tasks.Task SendMailFromGroupNotificationAsync(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Notification.Domain.GroupMessages message) {
            return base.Channel.SendMailFromGroupNotificationAsync(istanceIdentifier, idUser, moduleCode, message);
        }
        
        public void SendMailMessagesFromTemplate(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.MessageSettings mailSettings, System.Collections.Generic.List<lm.Comol.Core.Mail.Messages.dtoMailTranslatedMessage> messages, lm.Comol.Core.Mail.Messages.dtoBaseMailTemplate template, lm.Comol.Core.DomainModel.ModuleObject obj, int idCommunity, bool isPortal, System.Collections.Generic.List<string> attachments, string attachmentPath, bool saveMessage) {
            base.Channel.SendMailMessagesFromTemplate(istanceIdentifier, idUser, moduleCode, mailSettings, messages, template, obj, idCommunity, isPortal, attachments, attachmentPath, saveMessage);
        }
        
        public System.Threading.Tasks.Task SendMailMessagesFromTemplateAsync(string istanceIdentifier, int idUser, string moduleCode, lm.Comol.Core.Msmq.Services.Notifications.Service.SrvMailSender.MessageSettings mailSettings, System.Collections.Generic.List<lm.Comol.Core.Mail.Messages.dtoMailTranslatedMessage> messages, lm.Comol.Core.Mail.Messages.dtoBaseMailTemplate template, lm.Comol.Core.DomainModel.ModuleObject obj, int idCommunity, bool isPortal, System.Collections.Generic.List<string> attachments, string attachmentPath, bool saveMessage) {
            return base.Channel.SendMailMessagesFromTemplateAsync(istanceIdentifier, idUser, moduleCode, mailSettings, messages, template, obj, idCommunity, isPortal, attachments, attachmentPath, saveMessage);
        }
    }
}
