//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransfer.Core.ServiceReferenceUnzip {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUnzip.IUnzipMQService")]
    public interface IUnzipMQService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUnzipMQService/FileUnzipNotification")]
        void FileUnzipNotification(string Platform, System.Guid FileId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnzipMQServiceChannel : FileTransfer.Core.ServiceReferenceUnzip.IUnzipMQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnzipMQServiceClient : System.ServiceModel.ClientBase<FileTransfer.Core.ServiceReferenceUnzip.IUnzipMQService>, FileTransfer.Core.ServiceReferenceUnzip.IUnzipMQService {
        
        public UnzipMQServiceClient() {
        }
        
        public UnzipMQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnzipMQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnzipMQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnzipMQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void FileUnzipNotification(string Platform, System.Guid FileId) {
            base.Channel.FileUnzipNotification(Platform, FileId);
        }
    }
}
