'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WS_OnLine
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderItemsBy", [Namespace]:="http://tempuri.org/")>  _
    Public Enum OrderItemsBy As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UserName = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CommunityName = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LastAction = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ModuleName = 4
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserAction", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserAction
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As System.Guid
        
        Private ActionDateField As Date
        
        Private CommunityIDField As Integer
        
        Private InteractionField As WS_OnLine.InteractionType
        
        Private ModuleIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObjectActionsField As System.Collections.Generic.List(Of WS_OnLine.ObjectAction)
        
        Private PersonIDField As Integer
        
        Private TypeField As Integer
        
        Private WorkingSessionIDField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientIPadressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProxyIPadressField As String
        
        Private PersonRoleIDField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As System.Guid
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property ActionDate() As Date
            Get
                Return Me.ActionDateField
            End Get
            Set
                If (Me.ActionDateField.Equals(value) <> true) Then
                    Me.ActionDateField = value
                    Me.RaisePropertyChanged("ActionDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property CommunityID() As Integer
            Get
                Return Me.CommunityIDField
            End Get
            Set
                If (Me.CommunityIDField.Equals(value) <> true) Then
                    Me.CommunityIDField = value
                    Me.RaisePropertyChanged("CommunityID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Interaction() As WS_OnLine.InteractionType
            Get
                Return Me.InteractionField
            End Get
            Set
                If (Me.InteractionField.Equals(value) <> true) Then
                    Me.InteractionField = value
                    Me.RaisePropertyChanged("Interaction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property ModuleID() As Integer
            Get
                Return Me.ModuleIDField
            End Get
            Set
                If (Me.ModuleIDField.Equals(value) <> true) Then
                    Me.ModuleIDField = value
                    Me.RaisePropertyChanged("ModuleID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property ObjectActions() As System.Collections.Generic.List(Of WS_OnLine.ObjectAction)
            Get
                Return Me.ObjectActionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObjectActionsField, value) <> true) Then
                    Me.ObjectActionsField = value
                    Me.RaisePropertyChanged("ObjectActions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property PersonID() As Integer
            Get
                Return Me.PersonIDField
            End Get
            Set
                If (Me.PersonIDField.Equals(value) <> true) Then
                    Me.PersonIDField = value
                    Me.RaisePropertyChanged("PersonID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property Type() As Integer
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property WorkingSessionID() As System.Guid
            Get
                Return Me.WorkingSessionIDField
            End Get
            Set
                If (Me.WorkingSessionIDField.Equals(value) <> true) Then
                    Me.WorkingSessionIDField = value
                    Me.RaisePropertyChanged("WorkingSessionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property ClientIPadress() As String
            Get
                Return Me.ClientIPadressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientIPadressField, value) <> true) Then
                    Me.ClientIPadressField = value
                    Me.RaisePropertyChanged("ClientIPadress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property ProxyIPadress() As String
            Get
                Return Me.ProxyIPadressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProxyIPadressField, value) <> true) Then
                    Me.ProxyIPadressField = value
                    Me.RaisePropertyChanged("ProxyIPadress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=11)>  _
        Public Property PersonRoleID() As Integer
            Get
                Return Me.PersonRoleIDField
            End Get
            Set
                If (Me.PersonRoleIDField.Equals(value) <> true) Then
                    Me.PersonRoleIDField = value
                    Me.RaisePropertyChanged("PersonRoleID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InteractionType", [Namespace]:="http://tempuri.org/")>  _
    Public Enum InteractionType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UserWithUser = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UserWithCommunityAdministrator = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UserWithLearningObject = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Generic = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SystemToSystem = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SystemToUser = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SystemToModule = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ModuleToSystem = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ModuleToModule = 9
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ObjectAction", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ObjectAction
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private ModuleIDField As Integer
        
        Private ObjectTypeIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValueIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ModuleID() As Integer
            Get
                Return Me.ModuleIDField
            End Get
            Set
                If (Me.ModuleIDField.Equals(value) <> true) Then
                    Me.ModuleIDField = value
                    Me.RaisePropertyChanged("ModuleID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ObjectTypeId() As Integer
            Get
                Return Me.ObjectTypeIdField
            End Get
            Set
                If (Me.ObjectTypeIdField.Equals(value) <> true) Then
                    Me.ObjectTypeIdField = value
                    Me.RaisePropertyChanged("ObjectTypeId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValueID() As String
            Get
                Return Me.ValueIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueIDField, value) <> true) Then
                    Me.ValueIDField = value
                    Me.RaisePropertyChanged("ValueID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfDtoAccess", [Namespace]:="http://tempuri.org/", ItemName:="dtoAccess"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfDtoAccess
        Inherits System.Collections.Generic.List(Of WS_OnLine.dtoAccess)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dtoAccess", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dtoAccess
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Integer
        
        Private WorkingSessionIDField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property WorkingSessionID() As System.Guid
            Get
                Return Me.WorkingSessionIDField
            End Get
            Set
                If (Me.WorkingSessionIDField.Equals(value) <> true) Then
                    Me.WorkingSessionIDField = value
                    Me.RaisePropertyChanged("WorkingSessionID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OnLineUserAction", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OnLineUserAction
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As System.Guid
        
        Private ActionDateField As Date
        
        Private AccessDateField As Date
        
        Private CommunityIDField As Integer
        
        Private ModuleIDField As Integer
        
        Private PersonIDField As Integer
        
        Private TypeField As Integer
        
        Private WorkingSessionIDField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientIPadressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProxyIPadressField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As System.Guid
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property ActionDate() As Date
            Get
                Return Me.ActionDateField
            End Get
            Set
                If (Me.ActionDateField.Equals(value) <> true) Then
                    Me.ActionDateField = value
                    Me.RaisePropertyChanged("ActionDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property AccessDate() As Date
            Get
                Return Me.AccessDateField
            End Get
            Set
                If (Me.AccessDateField.Equals(value) <> true) Then
                    Me.AccessDateField = value
                    Me.RaisePropertyChanged("AccessDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property CommunityID() As Integer
            Get
                Return Me.CommunityIDField
            End Get
            Set
                If (Me.CommunityIDField.Equals(value) <> true) Then
                    Me.CommunityIDField = value
                    Me.RaisePropertyChanged("CommunityID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property ModuleID() As Integer
            Get
                Return Me.ModuleIDField
            End Get
            Set
                If (Me.ModuleIDField.Equals(value) <> true) Then
                    Me.ModuleIDField = value
                    Me.RaisePropertyChanged("ModuleID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property PersonID() As Integer
            Get
                Return Me.PersonIDField
            End Get
            Set
                If (Me.PersonIDField.Equals(value) <> true) Then
                    Me.PersonIDField = value
                    Me.RaisePropertyChanged("PersonID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property Type() As Integer
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property WorkingSessionID() As System.Guid
            Get
                Return Me.WorkingSessionIDField
            End Get
            Set
                If (Me.WorkingSessionIDField.Equals(value) <> true) Then
                    Me.WorkingSessionIDField = value
                    Me.RaisePropertyChanged("WorkingSessionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property ClientIPadress() As String
            Get
                Return Me.ClientIPadressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientIPadressField, value) <> true) Then
                    Me.ClientIPadressField = value
                    Me.RaisePropertyChanged("ClientIPadress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property ProxyIPadress() As String
            Get
                Return Me.ProxyIPadressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProxyIPadressField, value) <> true) Then
                    Me.ProxyIPadressField = value
                    Me.RaisePropertyChanged("ProxyIPadress")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WS_OnLine.UserOnlineSoap")>  _
    Public Interface UserOnlineSoap
        
        'CODEGEN: Generating message contract since element name GetGenericUsersOnlineResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetGenericUsersOnline", ReplyAction:="*")>  _
        Function GetGenericUsersOnline(ByVal request As WS_OnLine.GetGenericUsersOnlineRequest) As WS_OnLine.GetGenericUsersOnlineResponse
        
        'CODEGEN: Generating message contract since element name oDtoAccess from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSelectedUsersOnline", ReplyAction:="*")>  _
        Function GetSelectedUsersOnline(ByVal request As WS_OnLine.GetSelectedUsersOnlineRequest) As WS_OnLine.GetSelectedUsersOnlineResponse
        
        'CODEGEN: Generating message contract since element name GetUsersOnlineIDResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUsersOnlineID", ReplyAction:="*")>  _
        Function GetUsersOnlineID(ByVal request As WS_OnLine.GetUsersOnlineIDRequest) As WS_OnLine.GetUsersOnlineIDResponse
        
        'CODEGEN: Generating message contract since the wrapper name (GetUsersOnlineCommunityID) of message GetUsersOnlineCommunityID does not match the default value (GetUsersOnlineCommunitiesID)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUsersOnlineCommunityID", ReplyAction:="*")>  _
        Function GetUsersOnlineCommunitiesID(ByVal request As WS_OnLine.GetUsersOnlineCommunityID) As WS_OnLine.GetUsersOnlineCommunityID1
        
        'CODEGEN: Generating message contract since element name GetUsersOnlineModulesIDResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUsersOnlineModulesID", ReplyAction:="*")>  _
        Function GetUsersOnlineModulesID(ByVal request As WS_OnLine.GetUsersOnlineModulesIDRequest) As WS_OnLine.GetUsersOnlineModulesIDResponse
        
        'CODEGEN: Generating message contract since the wrapper name (UsersOnlineCount) of message UsersOnlineCount does not match the default value (UserOnlineCount)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UsersOnlineCount", ReplyAction:="*")>  _
        Function UserOnlineCount(ByVal request As WS_OnLine.UsersOnlineCount) As WS_OnLine.UsersOnlineCount1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WorkingSessionOnlineCount", ReplyAction:="*")>  _
        Function WorkingSessionOnlineCount(ByVal CommunityID As Integer, ByVal ModuleID As Integer) As Integer
        
        'CODEGEN: Generating message contract since element name GetOnLineActionsResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetOnLineActions", ReplyAction:="*")>  _
        Function GetOnLineActions(ByVal request As WS_OnLine.GetOnLineActionsRequest) As WS_OnLine.GetOnLineActionsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (Test_RecuperaTutteLeAzioniDallaCache) of message Test_RecuperaTutteLeAzioniDallaCache does not match the default value (_Test_RecuperaTutteLeAzioniDallaCache)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Test_RecuperaTutteLeAzioniDallaCache", ReplyAction:="*")>  _
        Function _Test_RecuperaTutteLeAzioniDallaCache(ByVal request As WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache) As WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache1
        
        'CODEGEN: Generating message contract since the wrapper name (Test_RecuperaElementiMAxUnoraFa) of message Test_RecuperaElementiMAxUnoraFa does not match the default value (_Test_RecuperaElementiMAxUnoraFa)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Test_RecuperaElementiMAxUnoraFa", ReplyAction:="*")>  _
        Function _Test_RecuperaElementiMAxUnoraFa(ByVal request As WS_OnLine.Test_RecuperaElementiMAxUnoraFa) As WS_OnLine.Test_RecuperaElementiMAxUnoraFa1
        
        'CODEGEN: Generating message contract since the wrapper name (Test_RemoveNotRecent) of message Test_RemoveNotRecent does not match the default value (_Test_RemoveNotRecent)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Test_RemoveNotRecent", ReplyAction:="*")>  _
        Function _Test_RemoveNotRecent(ByVal request As WS_OnLine.Test_RemoveNotRecent) As WS_OnLine.Test_RemoveNotRecent1
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGenericUsersOnlineRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGenericUsersOnline", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetGenericUsersOnlineRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetGenericUsersOnlineRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGenericUsersOnlineRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CommunityID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public ModuleID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public PageSize As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public PageIndex As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Order As WS_OnLine.OrderItemsBy
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Ascending As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CommunityID As Integer, ByVal ModuleID As Integer, ByVal PageSize As Integer, ByVal PageIndex As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean)
            MyBase.New
            Me.CommunityID = CommunityID
            Me.ModuleID = ModuleID
            Me.PageSize = PageSize
            Me.PageIndex = PageIndex
            Me.Order = Order
            Me.Ascending = Ascending
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetGenericUsersOnlineResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetGenericUsersOnlineResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetGenericUsersOnlineResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetGenericUsersOnlineResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetGenericUsersOnlineResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetGenericUsersOnlineResult As System.Collections.Generic.List(Of WS_OnLine.UserAction)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetGenericUsersOnlineResult As System.Collections.Generic.List(Of WS_OnLine.UserAction))
            MyBase.New
            Me.GetGenericUsersOnlineResult = GetGenericUsersOnlineResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSelectedUsersOnlineRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSelectedUsersOnline", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetSelectedUsersOnlineRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetSelectedUsersOnlineRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSelectedUsersOnlineRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public oDtoAccess As WS_OnLine.ArrayOfDtoAccess
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public oOrder As WS_OnLine.OrderItemsBy
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal oDtoAccess As WS_OnLine.ArrayOfDtoAccess, ByVal oOrder As WS_OnLine.OrderItemsBy)
            MyBase.New
            Me.oDtoAccess = oDtoAccess
            Me.oOrder = oOrder
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetSelectedUsersOnlineResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetSelectedUsersOnlineResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetSelectedUsersOnlineResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetSelectedUsersOnlineResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetSelectedUsersOnlineResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetSelectedUsersOnlineResult As System.Collections.Generic.List(Of WS_OnLine.UserAction)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetSelectedUsersOnlineResult As System.Collections.Generic.List(Of WS_OnLine.UserAction))
            MyBase.New
            Me.GetSelectedUsersOnlineResult = GetSelectedUsersOnlineResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUsersOnlineIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUsersOnlineID", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetUsersOnlineIDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetUsersOnlineIDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUsersOnlineIDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CommunityID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public ModuleID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Order As WS_OnLine.OrderItemsBy
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Ascending As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CommunityID As Integer, ByVal ModuleID As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean)
            MyBase.New
            Me.CommunityID = CommunityID
            Me.ModuleID = ModuleID
            Me.Order = Order
            Me.Ascending = Ascending
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUsersOnlineIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUsersOnlineIDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetUsersOnlineIDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetUsersOnlineIDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUsersOnlineIDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUsersOnlineIDResult As WS_OnLine.ArrayOfDtoAccess
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUsersOnlineIDResult As WS_OnLine.ArrayOfDtoAccess)
            MyBase.New
            Me.GetUsersOnlineIDResult = GetUsersOnlineIDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetUsersOnlineCommunityID", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetUsersOnlineCommunityID
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ModuleID As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public Order As WS_OnLine.OrderItemsBy
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public Ascending As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ModuleID As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean)
            MyBase.New
            Me.ModuleID = ModuleID
            Me.Order = Order
            Me.Ascending = Ascending
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetUsersOnlineCommunityIDResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetUsersOnlineCommunityID1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetUsersOnlineCommunityIDResult As WS_OnLine.ArrayOfDtoAccess
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUsersOnlineCommunityIDResult As WS_OnLine.ArrayOfDtoAccess)
            MyBase.New
            Me.GetUsersOnlineCommunityIDResult = GetUsersOnlineCommunityIDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUsersOnlineModulesIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUsersOnlineModulesID", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetUsersOnlineModulesIDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetUsersOnlineModulesIDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUsersOnlineModulesIDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CommunityID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Order As WS_OnLine.OrderItemsBy
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Ascending As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CommunityID As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean)
            MyBase.New
            Me.CommunityID = CommunityID
            Me.Order = Order
            Me.Ascending = Ascending
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUsersOnlineModulesIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUsersOnlineModulesIDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetUsersOnlineModulesIDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetUsersOnlineModulesIDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUsersOnlineModulesIDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUsersOnlineModulesIDResult As WS_OnLine.ArrayOfDtoAccess
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUsersOnlineModulesIDResult As WS_OnLine.ArrayOfDtoAccess)
            MyBase.New
            Me.GetUsersOnlineModulesIDResult = GetUsersOnlineModulesIDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UsersOnlineCount", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class UsersOnlineCount
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CommunityID As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public ModuleID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CommunityID As Integer, ByVal ModuleID As Integer)
            MyBase.New
            Me.CommunityID = CommunityID
            Me.ModuleID = ModuleID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UsersOnlineCountResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class UsersOnlineCount1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public UsersOnlineCountResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsersOnlineCountResult As Integer)
            MyBase.New
            Me.UsersOnlineCountResult = UsersOnlineCountResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOnLineActionsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOnLineActions", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetOnLineActionsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetOnLineActionsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetOnLineActionsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CommunityID As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public ModuleID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CommunityID As Integer, ByVal ModuleID As Integer)
            MyBase.New
            Me.CommunityID = CommunityID
            Me.ModuleID = ModuleID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOnLineActionsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOnLineActionsResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_OnLine.GetOnLineActionsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_OnLine.GetOnLineActionsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetOnLineActionsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetOnLineActionsResult As System.Collections.Generic.List(Of WS_OnLine.OnLineUserAction)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetOnLineActionsResult As System.Collections.Generic.List(Of WS_OnLine.OnLineUserAction))
            MyBase.New
            Me.GetOnLineActionsResult = GetOnLineActionsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Test_RecuperaTutteLeAzioniDallaCache", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Test_RecuperaTutteLeAzioniDallaCache
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Test_RecuperaTutteLeAzioniDallaCacheResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Test_RecuperaTutteLeAzioniDallaCache1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Test_RecuperaTutteLeAzioniDallaCacheResult As System.Collections.Generic.List(Of WS_OnLine.UserAction)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Test_RecuperaTutteLeAzioniDallaCacheResult As System.Collections.Generic.List(Of WS_OnLine.UserAction))
            MyBase.New
            Me.Test_RecuperaTutteLeAzioniDallaCacheResult = Test_RecuperaTutteLeAzioniDallaCacheResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Test_RecuperaElementiMAxUnoraFa", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Test_RecuperaElementiMAxUnoraFa
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Test_RecuperaElementiMAxUnoraFaResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Test_RecuperaElementiMAxUnoraFa1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Test_RecuperaElementiMAxUnoraFaResult As System.Collections.Generic.List(Of WS_OnLine.UserAction)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Test_RecuperaElementiMAxUnoraFaResult As System.Collections.Generic.List(Of WS_OnLine.UserAction))
            MyBase.New
            Me.Test_RecuperaElementiMAxUnoraFaResult = Test_RecuperaElementiMAxUnoraFaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Test_RemoveNotRecent", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Test_RemoveNotRecent
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Test_RemoveNotRecentResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Test_RemoveNotRecent1
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UserOnlineSoapChannel
        Inherits WS_OnLine.UserOnlineSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UserOnlineSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS_OnLine.UserOnlineSoap)
        Implements WS_OnLine.UserOnlineSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_GetGenericUsersOnline(ByVal request As WS_OnLine.GetGenericUsersOnlineRequest) As WS_OnLine.GetGenericUsersOnlineResponse Implements WS_OnLine.UserOnlineSoap.GetGenericUsersOnline
            Return MyBase.Channel.GetGenericUsersOnline(request)
        End Function
        
        Public Function GetGenericUsersOnline(ByVal CommunityID As Integer, ByVal ModuleID As Integer, ByVal PageSize As Integer, ByVal PageIndex As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean) As System.Collections.Generic.List(Of WS_OnLine.UserAction)
            Dim inValue As WS_OnLine.GetGenericUsersOnlineRequest = New WS_OnLine.GetGenericUsersOnlineRequest()
            inValue.Body = New WS_OnLine.GetGenericUsersOnlineRequestBody()
            inValue.Body.CommunityID = CommunityID
            inValue.Body.ModuleID = ModuleID
            inValue.Body.PageSize = PageSize
            inValue.Body.PageIndex = PageIndex
            inValue.Body.Order = Order
            inValue.Body.Ascending = Ascending
            Dim retVal As WS_OnLine.GetGenericUsersOnlineResponse = CType(Me,WS_OnLine.UserOnlineSoap).GetGenericUsersOnline(inValue)
            Return retVal.Body.GetGenericUsersOnlineResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_GetSelectedUsersOnline(ByVal request As WS_OnLine.GetSelectedUsersOnlineRequest) As WS_OnLine.GetSelectedUsersOnlineResponse Implements WS_OnLine.UserOnlineSoap.GetSelectedUsersOnline
            Return MyBase.Channel.GetSelectedUsersOnline(request)
        End Function
        
        Public Function GetSelectedUsersOnline(ByVal oDtoAccess As WS_OnLine.ArrayOfDtoAccess, ByVal oOrder As WS_OnLine.OrderItemsBy) As System.Collections.Generic.List(Of WS_OnLine.UserAction)
            Dim inValue As WS_OnLine.GetSelectedUsersOnlineRequest = New WS_OnLine.GetSelectedUsersOnlineRequest()
            inValue.Body = New WS_OnLine.GetSelectedUsersOnlineRequestBody()
            inValue.Body.oDtoAccess = oDtoAccess
            inValue.Body.oOrder = oOrder
            Dim retVal As WS_OnLine.GetSelectedUsersOnlineResponse = CType(Me,WS_OnLine.UserOnlineSoap).GetSelectedUsersOnline(inValue)
            Return retVal.Body.GetSelectedUsersOnlineResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_GetUsersOnlineID(ByVal request As WS_OnLine.GetUsersOnlineIDRequest) As WS_OnLine.GetUsersOnlineIDResponse Implements WS_OnLine.UserOnlineSoap.GetUsersOnlineID
            Return MyBase.Channel.GetUsersOnlineID(request)
        End Function
        
        Public Function GetUsersOnlineID(ByVal CommunityID As Integer, ByVal ModuleID As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean) As WS_OnLine.ArrayOfDtoAccess
            Dim inValue As WS_OnLine.GetUsersOnlineIDRequest = New WS_OnLine.GetUsersOnlineIDRequest()
            inValue.Body = New WS_OnLine.GetUsersOnlineIDRequestBody()
            inValue.Body.CommunityID = CommunityID
            inValue.Body.ModuleID = ModuleID
            inValue.Body.Order = Order
            inValue.Body.Ascending = Ascending
            Dim retVal As WS_OnLine.GetUsersOnlineIDResponse = CType(Me,WS_OnLine.UserOnlineSoap).GetUsersOnlineID(inValue)
            Return retVal.Body.GetUsersOnlineIDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_GetUsersOnlineCommunitiesID(ByVal request As WS_OnLine.GetUsersOnlineCommunityID) As WS_OnLine.GetUsersOnlineCommunityID1 Implements WS_OnLine.UserOnlineSoap.GetUsersOnlineCommunitiesID
            Return MyBase.Channel.GetUsersOnlineCommunitiesID(request)
        End Function
        
        Public Function GetUsersOnlineCommunitiesID(ByVal ModuleID As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean) As WS_OnLine.ArrayOfDtoAccess
            Dim inValue As WS_OnLine.GetUsersOnlineCommunityID = New WS_OnLine.GetUsersOnlineCommunityID()
            inValue.ModuleID = ModuleID
            inValue.Order = Order
            inValue.Ascending = Ascending
            Dim retVal As WS_OnLine.GetUsersOnlineCommunityID1 = CType(Me,WS_OnLine.UserOnlineSoap).GetUsersOnlineCommunitiesID(inValue)
            Return retVal.GetUsersOnlineCommunityIDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_GetUsersOnlineModulesID(ByVal request As WS_OnLine.GetUsersOnlineModulesIDRequest) As WS_OnLine.GetUsersOnlineModulesIDResponse Implements WS_OnLine.UserOnlineSoap.GetUsersOnlineModulesID
            Return MyBase.Channel.GetUsersOnlineModulesID(request)
        End Function
        
        Public Function GetUsersOnlineModulesID(ByVal CommunityID As Integer, ByVal Order As WS_OnLine.OrderItemsBy, ByVal Ascending As Boolean) As WS_OnLine.ArrayOfDtoAccess
            Dim inValue As WS_OnLine.GetUsersOnlineModulesIDRequest = New WS_OnLine.GetUsersOnlineModulesIDRequest()
            inValue.Body = New WS_OnLine.GetUsersOnlineModulesIDRequestBody()
            inValue.Body.CommunityID = CommunityID
            inValue.Body.Order = Order
            inValue.Body.Ascending = Ascending
            Dim retVal As WS_OnLine.GetUsersOnlineModulesIDResponse = CType(Me,WS_OnLine.UserOnlineSoap).GetUsersOnlineModulesID(inValue)
            Return retVal.Body.GetUsersOnlineModulesIDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_UserOnlineCount(ByVal request As WS_OnLine.UsersOnlineCount) As WS_OnLine.UsersOnlineCount1 Implements WS_OnLine.UserOnlineSoap.UserOnlineCount
            Return MyBase.Channel.UserOnlineCount(request)
        End Function
        
        Public Function UserOnlineCount(ByVal CommunityID As Integer, ByVal ModuleID As Integer) As Integer
            Dim inValue As WS_OnLine.UsersOnlineCount = New WS_OnLine.UsersOnlineCount()
            inValue.CommunityID = CommunityID
            inValue.ModuleID = ModuleID
            Dim retVal As WS_OnLine.UsersOnlineCount1 = CType(Me,WS_OnLine.UserOnlineSoap).UserOnlineCount(inValue)
            Return retVal.UsersOnlineCountResult
        End Function
        
        Public Function WorkingSessionOnlineCount(ByVal CommunityID As Integer, ByVal ModuleID As Integer) As Integer Implements WS_OnLine.UserOnlineSoap.WorkingSessionOnlineCount
            Return MyBase.Channel.WorkingSessionOnlineCount(CommunityID, ModuleID)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap_GetOnLineActions(ByVal request As WS_OnLine.GetOnLineActionsRequest) As WS_OnLine.GetOnLineActionsResponse Implements WS_OnLine.UserOnlineSoap.GetOnLineActions
            Return MyBase.Channel.GetOnLineActions(request)
        End Function
        
        Public Function GetOnLineActions(ByVal CommunityID As Integer, ByVal ModuleID As Integer) As System.Collections.Generic.List(Of WS_OnLine.OnLineUserAction)
            Dim inValue As WS_OnLine.GetOnLineActionsRequest = New WS_OnLine.GetOnLineActionsRequest()
            inValue.Body = New WS_OnLine.GetOnLineActionsRequestBody()
            inValue.Body.CommunityID = CommunityID
            inValue.Body.ModuleID = ModuleID
            Dim retVal As WS_OnLine.GetOnLineActionsResponse = CType(Me,WS_OnLine.UserOnlineSoap).GetOnLineActions(inValue)
            Return retVal.Body.GetOnLineActionsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap__Test_RecuperaTutteLeAzioniDallaCache(ByVal request As WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache) As WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache1 Implements WS_OnLine.UserOnlineSoap._Test_RecuperaTutteLeAzioniDallaCache
            Return MyBase.Channel._Test_RecuperaTutteLeAzioniDallaCache(request)
        End Function
        
        Public Function _Test_RecuperaTutteLeAzioniDallaCache() As System.Collections.Generic.List(Of WS_OnLine.UserAction)
            Dim inValue As WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache = New WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache()
            Dim retVal As WS_OnLine.Test_RecuperaTutteLeAzioniDallaCache1 = CType(Me,WS_OnLine.UserOnlineSoap)._Test_RecuperaTutteLeAzioniDallaCache(inValue)
            Return retVal.Test_RecuperaTutteLeAzioniDallaCacheResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap__Test_RecuperaElementiMAxUnoraFa(ByVal request As WS_OnLine.Test_RecuperaElementiMAxUnoraFa) As WS_OnLine.Test_RecuperaElementiMAxUnoraFa1 Implements WS_OnLine.UserOnlineSoap._Test_RecuperaElementiMAxUnoraFa
            Return MyBase.Channel._Test_RecuperaElementiMAxUnoraFa(request)
        End Function
        
        Public Function _Test_RecuperaElementiMAxUnoraFa() As System.Collections.Generic.List(Of WS_OnLine.UserAction)
            Dim inValue As WS_OnLine.Test_RecuperaElementiMAxUnoraFa = New WS_OnLine.Test_RecuperaElementiMAxUnoraFa()
            Dim retVal As WS_OnLine.Test_RecuperaElementiMAxUnoraFa1 = CType(Me,WS_OnLine.UserOnlineSoap)._Test_RecuperaElementiMAxUnoraFa(inValue)
            Return retVal.Test_RecuperaElementiMAxUnoraFaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_OnLine_UserOnlineSoap__Test_RemoveNotRecent(ByVal request As WS_OnLine.Test_RemoveNotRecent) As WS_OnLine.Test_RemoveNotRecent1 Implements WS_OnLine.UserOnlineSoap._Test_RemoveNotRecent
            Return MyBase.Channel._Test_RemoveNotRecent(request)
        End Function
        
        Public Sub _Test_RemoveNotRecent()
            Dim inValue As WS_OnLine.Test_RemoveNotRecent = New WS_OnLine.Test_RemoveNotRecent()
            Dim retVal As WS_OnLine.Test_RemoveNotRecent1 = CType(Me,WS_OnLine.UserOnlineSoap)._Test_RemoveNotRecent(inValue)
        End Sub
    End Class
End Namespace
