//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lm.Notification.Service.SRVcoreCommunityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRVcoreCommunityService.CommunityServicesSoap")]
    public interface CommunityServicesSoap {
        
        // CODEGEN: Generating message contract since element name GetCommunityMembersIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommunityMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDResponse GetCommunityMembersID(lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetCommunityRoleMembersIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommunityRoleMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDResponse GetCommunityRoleMembersID(lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetPermissionMembersIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPermissionMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDResponse GetPermissionMembersID(lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetPortalPermissionMembersIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortalPermissionMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDResponse GetPortalPermissionMembersID(lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name ModuleCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemGuidMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDResponse GetItemGuidMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name ModuleCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemIntMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDResponse GetItemIntMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name ModuleCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemLongMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDResponse GetItemLongMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequest request);
        
        // CODEGEN: Generating message contract since element name moduleCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemVersionLongMembersID", ReplyAction="*")]
        lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDResponse GetItemVersionLongMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommunityMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommunityMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequestBody Body;
        
        public GetCommunityMembersIDRequest() {
        }
        
        public GetCommunityMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommunityMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CommunityID;
        
        public GetCommunityMembersIDRequestBody() {
        }
        
        public GetCommunityMembersIDRequestBody(int CommunityID) {
            this.CommunityID = CommunityID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommunityMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommunityMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDResponseBody Body;
        
        public GetCommunityMembersIDResponse() {
        }
        
        public GetCommunityMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommunityMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetCommunityMembersIDResult;
        
        public GetCommunityMembersIDResponseBody() {
        }
        
        public GetCommunityMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetCommunityMembersIDResult) {
            this.GetCommunityMembersIDResult = GetCommunityMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommunityRoleMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommunityRoleMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequestBody Body;
        
        public GetCommunityRoleMembersIDRequest() {
        }
        
        public GetCommunityRoleMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommunityRoleMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CommunityID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int RoleID;
        
        public GetCommunityRoleMembersIDRequestBody() {
        }
        
        public GetCommunityRoleMembersIDRequestBody(int CommunityID, int RoleID) {
            this.CommunityID = CommunityID;
            this.RoleID = RoleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommunityRoleMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommunityRoleMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDResponseBody Body;
        
        public GetCommunityRoleMembersIDResponse() {
        }
        
        public GetCommunityRoleMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommunityRoleMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetCommunityRoleMembersIDResult;
        
        public GetCommunityRoleMembersIDResponseBody() {
        }
        
        public GetCommunityRoleMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetCommunityRoleMembersIDResult) {
            this.GetCommunityRoleMembersIDResult = GetCommunityRoleMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissionMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissionMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequestBody Body;
        
        public GetPermissionMembersIDRequest() {
        }
        
        public GetPermissionMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissionMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CommunityID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Permission;
        
        public GetPermissionMembersIDRequestBody() {
        }
        
        public GetPermissionMembersIDRequestBody(int CommunityID, int ServiceID, int Permission) {
            this.CommunityID = CommunityID;
            this.ServiceID = ServiceID;
            this.Permission = Permission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissionMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissionMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDResponseBody Body;
        
        public GetPermissionMembersIDResponse() {
        }
        
        public GetPermissionMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissionMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetPermissionMembersIDResult;
        
        public GetPermissionMembersIDResponseBody() {
        }
        
        public GetPermissionMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetPermissionMembersIDResult) {
            this.GetPermissionMembersIDResult = GetPermissionMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPortalPermissionMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPortalPermissionMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequestBody Body;
        
        public GetPortalPermissionMembersIDRequest() {
        }
        
        public GetPortalPermissionMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPortalPermissionMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ServiceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Permission;
        
        public GetPortalPermissionMembersIDRequestBody() {
        }
        
        public GetPortalPermissionMembersIDRequestBody(int ServiceID, int Permission) {
            this.ServiceID = ServiceID;
            this.Permission = Permission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPortalPermissionMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPortalPermissionMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDResponseBody Body;
        
        public GetPortalPermissionMembersIDResponse() {
        }
        
        public GetPortalPermissionMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPortalPermissionMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetPortalPermissionMembersIDResult;
        
        public GetPortalPermissionMembersIDResponseBody() {
        }
        
        public GetPortalPermissionMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetPortalPermissionMembersIDResult) {
            this.GetPortalPermissionMembersIDResult = GetPortalPermissionMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemGuidMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemGuidMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequestBody Body;
        
        public GetItemGuidMembersIDRequest() {
        }
        
        public GetItemGuidMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemGuidMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CommunityID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModuleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid ItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int objectTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Permission;
        
        public GetItemGuidMembersIDRequestBody() {
        }
        
        public GetItemGuidMembersIDRequestBody(int CommunityID, string ModuleCode, System.Guid ItemID, int objectTypeID, int Permission) {
            this.CommunityID = CommunityID;
            this.ModuleCode = ModuleCode;
            this.ItemID = ItemID;
            this.objectTypeID = objectTypeID;
            this.Permission = Permission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemGuidMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemGuidMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDResponseBody Body;
        
        public GetItemGuidMembersIDResponse() {
        }
        
        public GetItemGuidMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemGuidMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemGuidMembersIDResult;
        
        public GetItemGuidMembersIDResponseBody() {
        }
        
        public GetItemGuidMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemGuidMembersIDResult) {
            this.GetItemGuidMembersIDResult = GetItemGuidMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemIntMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemIntMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequestBody Body;
        
        public GetItemIntMembersIDRequest() {
        }
        
        public GetItemIntMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemIntMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CommunityID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModuleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int objectTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Permission;
        
        public GetItemIntMembersIDRequestBody() {
        }
        
        public GetItemIntMembersIDRequestBody(int CommunityID, string ModuleCode, int ItemID, int objectTypeID, int Permission) {
            this.CommunityID = CommunityID;
            this.ModuleCode = ModuleCode;
            this.ItemID = ItemID;
            this.objectTypeID = objectTypeID;
            this.Permission = Permission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemIntMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemIntMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDResponseBody Body;
        
        public GetItemIntMembersIDResponse() {
        }
        
        public GetItemIntMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemIntMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemIntMembersIDResult;
        
        public GetItemIntMembersIDResponseBody() {
        }
        
        public GetItemIntMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemIntMembersIDResult) {
            this.GetItemIntMembersIDResult = GetItemIntMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemLongMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemLongMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequestBody Body;
        
        public GetItemLongMembersIDRequest() {
        }
        
        public GetItemLongMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemLongMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CommunityID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModuleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long ItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int objectTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Permission;
        
        public GetItemLongMembersIDRequestBody() {
        }
        
        public GetItemLongMembersIDRequestBody(int CommunityID, string ModuleCode, long ItemID, int objectTypeID, int Permission) {
            this.CommunityID = CommunityID;
            this.ModuleCode = ModuleCode;
            this.ItemID = ItemID;
            this.objectTypeID = objectTypeID;
            this.Permission = Permission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemLongMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemLongMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDResponseBody Body;
        
        public GetItemLongMembersIDResponse() {
        }
        
        public GetItemLongMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemLongMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemLongMembersIDResult;
        
        public GetItemLongMembersIDResponseBody() {
        }
        
        public GetItemLongMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemLongMembersIDResult) {
            this.GetItemLongMembersIDResult = GetItemLongMembersIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemVersionLongMembersIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemVersionLongMembersID", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequestBody Body;
        
        public GetItemVersionLongMembersIDRequest() {
        }
        
        public GetItemVersionLongMembersIDRequest(lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemVersionLongMembersIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCommunity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string moduleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long idItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long idVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int objectTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int permission;
        
        public GetItemVersionLongMembersIDRequestBody() {
        }
        
        public GetItemVersionLongMembersIDRequestBody(int idCommunity, string moduleCode, long idItem, long idVersion, int objectTypeID, int permission) {
            this.idCommunity = idCommunity;
            this.moduleCode = moduleCode;
            this.idItem = idItem;
            this.idVersion = idVersion;
            this.objectTypeID = objectTypeID;
            this.permission = permission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemVersionLongMembersIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemVersionLongMembersIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDResponseBody Body;
        
        public GetItemVersionLongMembersIDResponse() {
        }
        
        public GetItemVersionLongMembersIDResponse(lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemVersionLongMembersIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemVersionLongMembersIDResult;
        
        public GetItemVersionLongMembersIDResponseBody() {
        }
        
        public GetItemVersionLongMembersIDResponseBody(lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemVersionLongMembersIDResult) {
            this.GetItemVersionLongMembersIDResult = GetItemVersionLongMembersIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommunityServicesSoapChannel : lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunityServicesSoapClient : System.ServiceModel.ClientBase<lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap>, lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap {
        
        public CommunityServicesSoapClient() {
        }
        
        public CommunityServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunityServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunityServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunityServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetCommunityMembersID(lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequest request) {
            return base.Channel.GetCommunityMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetCommunityMembersID(int CommunityID) {
            lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDRequestBody();
            inValue.Body.CommunityID = CommunityID;
            lm.Notification.Service.SRVcoreCommunityService.GetCommunityMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetCommunityMembersID(inValue);
            return retVal.Body.GetCommunityMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetCommunityRoleMembersID(lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequest request) {
            return base.Channel.GetCommunityRoleMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetCommunityRoleMembersID(int CommunityID, int RoleID) {
            lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDRequestBody();
            inValue.Body.CommunityID = CommunityID;
            inValue.Body.RoleID = RoleID;
            lm.Notification.Service.SRVcoreCommunityService.GetCommunityRoleMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetCommunityRoleMembersID(inValue);
            return retVal.Body.GetCommunityRoleMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetPermissionMembersID(lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequest request) {
            return base.Channel.GetPermissionMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetPermissionMembersID(int CommunityID, int ServiceID, int Permission) {
            lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDRequestBody();
            inValue.Body.CommunityID = CommunityID;
            inValue.Body.ServiceID = ServiceID;
            inValue.Body.Permission = Permission;
            lm.Notification.Service.SRVcoreCommunityService.GetPermissionMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetPermissionMembersID(inValue);
            return retVal.Body.GetPermissionMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetPortalPermissionMembersID(lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequest request) {
            return base.Channel.GetPortalPermissionMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetPortalPermissionMembersID(int ServiceID, int Permission) {
            lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDRequestBody();
            inValue.Body.ServiceID = ServiceID;
            inValue.Body.Permission = Permission;
            lm.Notification.Service.SRVcoreCommunityService.GetPortalPermissionMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetPortalPermissionMembersID(inValue);
            return retVal.Body.GetPortalPermissionMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetItemGuidMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequest request) {
            return base.Channel.GetItemGuidMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemGuidMembersID(int CommunityID, string ModuleCode, System.Guid ItemID, int objectTypeID, int Permission) {
            lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDRequestBody();
            inValue.Body.CommunityID = CommunityID;
            inValue.Body.ModuleCode = ModuleCode;
            inValue.Body.ItemID = ItemID;
            inValue.Body.objectTypeID = objectTypeID;
            inValue.Body.Permission = Permission;
            lm.Notification.Service.SRVcoreCommunityService.GetItemGuidMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetItemGuidMembersID(inValue);
            return retVal.Body.GetItemGuidMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetItemIntMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequest request) {
            return base.Channel.GetItemIntMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemIntMembersID(int CommunityID, string ModuleCode, int ItemID, int objectTypeID, int Permission) {
            lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDRequestBody();
            inValue.Body.CommunityID = CommunityID;
            inValue.Body.ModuleCode = ModuleCode;
            inValue.Body.ItemID = ItemID;
            inValue.Body.objectTypeID = objectTypeID;
            inValue.Body.Permission = Permission;
            lm.Notification.Service.SRVcoreCommunityService.GetItemIntMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetItemIntMembersID(inValue);
            return retVal.Body.GetItemIntMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetItemLongMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequest request) {
            return base.Channel.GetItemLongMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemLongMembersID(int CommunityID, string ModuleCode, long ItemID, int objectTypeID, int Permission) {
            lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDRequestBody();
            inValue.Body.CommunityID = CommunityID;
            inValue.Body.ModuleCode = ModuleCode;
            inValue.Body.ItemID = ItemID;
            inValue.Body.objectTypeID = objectTypeID;
            inValue.Body.Permission = Permission;
            lm.Notification.Service.SRVcoreCommunityService.GetItemLongMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetItemLongMembersID(inValue);
            return retVal.Body.GetItemLongMembersIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDResponse lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap.GetItemVersionLongMembersID(lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequest request) {
            return base.Channel.GetItemVersionLongMembersID(request);
        }
        
        public lm.Notification.Service.SRVcoreCommunityService.ArrayOfInt GetItemVersionLongMembersID(int idCommunity, string moduleCode, long idItem, long idVersion, int objectTypeID, int permission) {
            lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequest inValue = new lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequest();
            inValue.Body = new lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDRequestBody();
            inValue.Body.idCommunity = idCommunity;
            inValue.Body.moduleCode = moduleCode;
            inValue.Body.idItem = idItem;
            inValue.Body.idVersion = idVersion;
            inValue.Body.objectTypeID = objectTypeID;
            inValue.Body.permission = permission;
            lm.Notification.Service.SRVcoreCommunityService.GetItemVersionLongMembersIDResponse retVal = ((lm.Notification.Service.SRVcoreCommunityService.CommunityServicesSoap)(this)).GetItemVersionLongMembersID(inValue);
            return retVal.Body.GetItemVersionLongMembersIDResult;
        }
    }
}
