'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WS_Chat
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", ConfigurationName:="WS_Chat.WS_ChatSoap")>  _
    Public Interface WS_ChatSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/IsAlive", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function IsAlive() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/Reset", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub Reset(ByVal SecureCode As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetErrorList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetErrorList(ByVal SecureCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RecuperaMessaggio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RecuperaMessaggio(ByVal IdUtente As Integer, ByVal IDComunita As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RecuperaMessaggioXML", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RecuperaMessaggioXML(ByVal IDUtente As Integer, ByVal IDComunita As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/InviaMessaggio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub InviaMessaggio(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As Integer, ByVal IDComunita As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/InviaMessaggioPrivato", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub InviaMessaggioPrivato(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As String, ByVal IDDest As String, ByVal IDComunita As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/NuovoUtente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub NuovoUtente(ByVal ID As Integer, ByVal Nome As String, ByVal IDComunita As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/NumeroUtenti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function NumeroUtenti(ByVal IDComunita As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RecuperaListaUtenti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RecuperaListaUtenti(ByVal IdUtente As Integer, ByVal IDComunita As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetLvl", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetLvl(ByVal Id As Integer, ByVal IDComunita As Integer) As Byte
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RemUtente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RemUtente(ByVal Id As Integer, ByVal IDComunita As Integer) As Byte
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/SetBlock", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub SetBlock(ByVal IdFrom As Integer, ByVal IdTo As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RemBlock", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub RemBlock(ByVal IdFrom As Integer, ByVal IdTo As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetBlockFrom", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetBlockFrom(ByVal IdFrom As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetBlockTo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetBlockTo(ByVal IdTo As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RecuperaTutti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RecuperaTutti(ByVal Id As Integer, ByVal IDComunita As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/SetLvl", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub SetLvl(ByVal IDAmm As Integer, ByVal IDSet As Integer, ByVal NewLvl As Byte, ByVal IDComunita As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/ResetMsg", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub ResetMsg(ByVal Id As Integer, ByVal IDComunita As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/DistruggiTutto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub DistruggiTutto(ByVal Credenziale As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/SendAllADM", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub SendAllADM(ByVal Credenziale As String, ByVal messaggio As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/IsUploadTime", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function IsUploadTime() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/IsUploadTimeCom", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function IsUploadTimeCom(ByVal IdCom As Integer) As Boolean
        
        'CODEGEN: Parameter 'File' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/UploadFile", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function UploadFile(ByVal request As WS_Chat.UploadFileRequest) As WS_Chat.UploadFileResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetFileList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetFileList(ByVal IDUt As Integer, ByVal IDComunita As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetTmpDir", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTmpDir(ByVal IDUt As Integer, ByVal IDComunita As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/RemFile", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function RemFile(ByVal FileName As String, ByVal IdUser As Integer, ByVal IDComunita As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/GetFileNum", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetFileNum(ByVal IDComunita As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/IsFileExist", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function IsFileExist(ByVal FileName As String, ByVal IDComunita As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaGetLvl", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AreaGetLvl(ByVal Id As Integer, ByVal IDArea As Integer) As Byte
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaNuovoUtente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub AreaNuovoUtente(ByVal ID As Integer, ByVal Nome As String, ByVal IDArea As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaRecuperaListaUtenti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AreaRecuperaListaUtenti(ByVal IdUtente As Integer, ByVal IDArea As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaInviaMessaggio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub AreaInviaMessaggio(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As Integer, ByVal IDArea As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaInviaMessaggioPrivato", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub AreaInviaMessaggioPrivato(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As String, ByVal IDDest As String, ByVal IDArea As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaRecuperaMessaggio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AreaRecuperaMessaggio(ByVal IdUtente As Integer, ByVal IDArea As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaRecuperaTutti", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function AreaRecuperaTutti(ByVal Id As Integer, ByVal IDArea As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaSetLvl", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub AreaSetLvl(ByVal IDAmm As Integer, ByVal IDSet As Integer, ByVal NewLvl As Byte, ByVal IDArea As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_Chat/WS_Chat/AreaResetMsg", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub AreaResetMsg(ByVal Id As Integer, ByVal IDArea As Integer)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UploadFile", WrapperNamespace:="http://tempuri.org/WS_Chat/WS_Chat", IsWrapped:=true)>  _
    Partial Public Class UploadFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public File() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=1)>  _
        Public FileName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=2)>  _
        Public UplName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=3)>  _
        Public IDUpl As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=4)>  _
        Public note As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=5)>  _
        Public IDComunita As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal File() As Byte, ByVal FileName As String, ByVal UplName As String, ByVal IDUpl As Integer, ByVal note As String, ByVal IDComunita As Integer)
            MyBase.New
            Me.File = File
            Me.FileName = FileName
            Me.UplName = UplName
            Me.IDUpl = IDUpl
            Me.note = note
            Me.IDComunita = IDComunita
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UploadFileResponse", WrapperNamespace:="http://tempuri.org/WS_Chat/WS_Chat", IsWrapped:=true)>  _
    Partial Public Class UploadFileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_Chat/WS_Chat", Order:=0)>  _
        Public UploadFileResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UploadFileResult As String)
            MyBase.New
            Me.UploadFileResult = UploadFileResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WS_ChatSoapChannel
        Inherits WS_Chat.WS_ChatSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WS_ChatSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS_Chat.WS_ChatSoap)
        Implements WS_Chat.WS_ChatSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function IsAlive() As Boolean Implements WS_Chat.WS_ChatSoap.IsAlive
            Return MyBase.Channel.IsAlive
        End Function
        
        Public Sub Reset(ByVal SecureCode As String) Implements WS_Chat.WS_ChatSoap.Reset
            MyBase.Channel.Reset(SecureCode)
        End Sub
        
        Public Function GetErrorList(ByVal SecureCode As String) As String Implements WS_Chat.WS_ChatSoap.GetErrorList
            Return MyBase.Channel.GetErrorList(SecureCode)
        End Function
        
        Public Function RecuperaMessaggio(ByVal IdUtente As Integer, ByVal IDComunita As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.RecuperaMessaggio
            Return MyBase.Channel.RecuperaMessaggio(IdUtente, IDComunita)
        End Function
        
        Public Function RecuperaMessaggioXML(ByVal IDUtente As Integer, ByVal IDComunita As Integer) As String Implements WS_Chat.WS_ChatSoap.RecuperaMessaggioXML
            Return MyBase.Channel.RecuperaMessaggioXML(IDUtente, IDComunita)
        End Function
        
        Public Sub InviaMessaggio(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As Integer, ByVal IDComunita As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String) Implements WS_Chat.WS_ChatSoap.InviaMessaggio
            MyBase.Channel.InviaMessaggio(Nome, Messaggio, IDPersona, IDComunita, IsBold, IsItalic, IsUnderline, TxtBgColor, TxtColor)
        End Sub
        
        Public Sub InviaMessaggioPrivato(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As String, ByVal IDDest As String, ByVal IDComunita As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String) Implements WS_Chat.WS_ChatSoap.InviaMessaggioPrivato
            MyBase.Channel.InviaMessaggioPrivato(Nome, Messaggio, IDPersona, IDDest, IDComunita, IsBold, IsItalic, IsUnderline, TxtBgColor, TxtColor)
        End Sub
        
        Public Sub NuovoUtente(ByVal ID As Integer, ByVal Nome As String, ByVal IDComunita As Integer) Implements WS_Chat.WS_ChatSoap.NuovoUtente
            MyBase.Channel.NuovoUtente(ID, Nome, IDComunita)
        End Sub
        
        Public Function NumeroUtenti(ByVal IDComunita As Integer) As Integer Implements WS_Chat.WS_ChatSoap.NumeroUtenti
            Return MyBase.Channel.NumeroUtenti(IDComunita)
        End Function
        
        Public Function RecuperaListaUtenti(ByVal IdUtente As Integer, ByVal IDComunita As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.RecuperaListaUtenti
            Return MyBase.Channel.RecuperaListaUtenti(IdUtente, IDComunita)
        End Function
        
        Public Function GetLvl(ByVal Id As Integer, ByVal IDComunita As Integer) As Byte Implements WS_Chat.WS_ChatSoap.GetLvl
            Return MyBase.Channel.GetLvl(Id, IDComunita)
        End Function
        
        Public Function RemUtente(ByVal Id As Integer, ByVal IDComunita As Integer) As Byte Implements WS_Chat.WS_ChatSoap.RemUtente
            Return MyBase.Channel.RemUtente(Id, IDComunita)
        End Function
        
        Public Sub SetBlock(ByVal IdFrom As Integer, ByVal IdTo As Integer) Implements WS_Chat.WS_ChatSoap.SetBlock
            MyBase.Channel.SetBlock(IdFrom, IdTo)
        End Sub
        
        Public Sub RemBlock(ByVal IdFrom As Integer, ByVal IdTo As Integer) Implements WS_Chat.WS_ChatSoap.RemBlock
            MyBase.Channel.RemBlock(IdFrom, IdTo)
        End Sub
        
        Public Function GetBlockFrom(ByVal IdFrom As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.GetBlockFrom
            Return MyBase.Channel.GetBlockFrom(IdFrom)
        End Function
        
        Public Function GetBlockTo(ByVal IdTo As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.GetBlockTo
            Return MyBase.Channel.GetBlockTo(IdTo)
        End Function
        
        Public Function RecuperaTutti(ByVal Id As Integer, ByVal IDComunita As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.RecuperaTutti
            Return MyBase.Channel.RecuperaTutti(Id, IDComunita)
        End Function
        
        Public Sub SetLvl(ByVal IDAmm As Integer, ByVal IDSet As Integer, ByVal NewLvl As Byte, ByVal IDComunita As Integer) Implements WS_Chat.WS_ChatSoap.SetLvl
            MyBase.Channel.SetLvl(IDAmm, IDSet, NewLvl, IDComunita)
        End Sub
        
        Public Sub ResetMsg(ByVal Id As Integer, ByVal IDComunita As Integer) Implements WS_Chat.WS_ChatSoap.ResetMsg
            MyBase.Channel.ResetMsg(Id, IDComunita)
        End Sub
        
        Public Sub DistruggiTutto(ByVal Credenziale As String) Implements WS_Chat.WS_ChatSoap.DistruggiTutto
            MyBase.Channel.DistruggiTutto(Credenziale)
        End Sub
        
        Public Sub SendAllADM(ByVal Credenziale As String, ByVal messaggio As String) Implements WS_Chat.WS_ChatSoap.SendAllADM
            MyBase.Channel.SendAllADM(Credenziale, messaggio)
        End Sub
        
        Public Function IsUploadTime() As Boolean Implements WS_Chat.WS_ChatSoap.IsUploadTime
            Return MyBase.Channel.IsUploadTime
        End Function
        
        Public Function IsUploadTimeCom(ByVal IdCom As Integer) As Boolean Implements WS_Chat.WS_ChatSoap.IsUploadTimeCom
            Return MyBase.Channel.IsUploadTimeCom(IdCom)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_Chat_WS_ChatSoap_UploadFile(ByVal request As WS_Chat.UploadFileRequest) As WS_Chat.UploadFileResponse Implements WS_Chat.WS_ChatSoap.UploadFile
            Return MyBase.Channel.UploadFile(request)
        End Function
        
        Public Function UploadFile(ByVal File() As Byte, ByVal FileName As String, ByVal UplName As String, ByVal IDUpl As Integer, ByVal note As String, ByVal IDComunita As Integer) As String
            Dim inValue As WS_Chat.UploadFileRequest = New WS_Chat.UploadFileRequest()
            inValue.File = File
            inValue.FileName = FileName
            inValue.UplName = UplName
            inValue.IDUpl = IDUpl
            inValue.note = note
            inValue.IDComunita = IDComunita
            Dim retVal As WS_Chat.UploadFileResponse = CType(Me,WS_Chat.WS_ChatSoap).UploadFile(inValue)
            Return retVal.UploadFileResult
        End Function
        
        Public Function GetFileList(ByVal IDUt As Integer, ByVal IDComunita As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.GetFileList
            Return MyBase.Channel.GetFileList(IDUt, IDComunita)
        End Function
        
        Public Function GetTmpDir(ByVal IDUt As Integer, ByVal IDComunita As Integer) As String Implements WS_Chat.WS_ChatSoap.GetTmpDir
            Return MyBase.Channel.GetTmpDir(IDUt, IDComunita)
        End Function
        
        Public Function RemFile(ByVal FileName As String, ByVal IdUser As Integer, ByVal IDComunita As Integer) As String Implements WS_Chat.WS_ChatSoap.RemFile
            Return MyBase.Channel.RemFile(FileName, IdUser, IDComunita)
        End Function
        
        Public Function GetFileNum(ByVal IDComunita As Integer) As Integer Implements WS_Chat.WS_ChatSoap.GetFileNum
            Return MyBase.Channel.GetFileNum(IDComunita)
        End Function
        
        Public Function IsFileExist(ByVal FileName As String, ByVal IDComunita As Integer) As Boolean Implements WS_Chat.WS_ChatSoap.IsFileExist
            Return MyBase.Channel.IsFileExist(FileName, IDComunita)
        End Function
        
        Public Function AreaGetLvl(ByVal Id As Integer, ByVal IDArea As Integer) As Byte Implements WS_Chat.WS_ChatSoap.AreaGetLvl
            Return MyBase.Channel.AreaGetLvl(Id, IDArea)
        End Function
        
        Public Sub AreaNuovoUtente(ByVal ID As Integer, ByVal Nome As String, ByVal IDArea As Integer) Implements WS_Chat.WS_ChatSoap.AreaNuovoUtente
            MyBase.Channel.AreaNuovoUtente(ID, Nome, IDArea)
        End Sub
        
        Public Function AreaRecuperaListaUtenti(ByVal IdUtente As Integer, ByVal IDArea As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.AreaRecuperaListaUtenti
            Return MyBase.Channel.AreaRecuperaListaUtenti(IdUtente, IDArea)
        End Function
        
        Public Sub AreaInviaMessaggio(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As Integer, ByVal IDArea As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String) Implements WS_Chat.WS_ChatSoap.AreaInviaMessaggio
            MyBase.Channel.AreaInviaMessaggio(Nome, Messaggio, IDPersona, IDArea, IsBold, IsItalic, IsUnderline, TxtBgColor, TxtColor)
        End Sub
        
        Public Sub AreaInviaMessaggioPrivato(ByVal Nome As String, ByVal Messaggio As String, ByVal IDPersona As String, ByVal IDDest As String, ByVal IDArea As Integer, ByVal IsBold As Boolean, ByVal IsItalic As Boolean, ByVal IsUnderline As Boolean, ByVal TxtBgColor As String, ByVal TxtColor As String) Implements WS_Chat.WS_ChatSoap.AreaInviaMessaggioPrivato
            MyBase.Channel.AreaInviaMessaggioPrivato(Nome, Messaggio, IDPersona, IDDest, IDArea, IsBold, IsItalic, IsUnderline, TxtBgColor, TxtColor)
        End Sub
        
        Public Function AreaRecuperaMessaggio(ByVal IdUtente As Integer, ByVal IDArea As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.AreaRecuperaMessaggio
            Return MyBase.Channel.AreaRecuperaMessaggio(IdUtente, IDArea)
        End Function
        
        Public Function AreaRecuperaTutti(ByVal Id As Integer, ByVal IDArea As Integer) As System.Data.DataSet Implements WS_Chat.WS_ChatSoap.AreaRecuperaTutti
            Return MyBase.Channel.AreaRecuperaTutti(Id, IDArea)
        End Function
        
        Public Sub AreaSetLvl(ByVal IDAmm As Integer, ByVal IDSet As Integer, ByVal NewLvl As Byte, ByVal IDArea As Integer) Implements WS_Chat.WS_ChatSoap.AreaSetLvl
            MyBase.Channel.AreaSetLvl(IDAmm, IDSet, NewLvl, IDArea)
        End Sub
        
        Public Sub AreaResetMsg(ByVal Id As Integer, ByVal IDArea As Integer) Implements WS_Chat.WS_ChatSoap.AreaResetMsg
            MyBase.Channel.AreaResetMsg(Id, IDArea)
        End Sub
    End Class
End Namespace
