'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FAQList

    '''<summary>
    '''LTpageTitle_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTpageTitle_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BTNShowAddFaq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNShowAddFaq As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''PNaddFaq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNaddFaq As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BTNAnnullaAddFaq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNAnnullaAddFaq As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTaddFaq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTaddFaq As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HFfaqId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFfaqId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LBcategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcategoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBLcategorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBLcategorie As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''LBdomanda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdomanda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXTquestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTquestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBrisposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrisposta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CTRLeditorText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLeditorText As Global.Comunita_OnLine.UC_Editor

    '''<summary>
    '''PnNoFaqs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnNoFaqs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RPTFaq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTFaq As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LTtitolettoCategorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTtitolettoCategorie As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BTNShowAddCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNShowAddCat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''PNaddCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNaddCat As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LBnomeCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBnomeCat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HFCatId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFCatId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TXTcatName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTcatName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNannullaAddCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNannullaAddCat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNaddCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNaddCat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HLcatNamTuttee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HLcatNamTuttee As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''RPTCats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTCats As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
