'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Submission

    '''<summary>
    '''CTRLheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLheader As Global.Comunita_OnLine.UC_CallHeader

    '''<summary>
    '''CTRLmodalPlayerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLmodalPlayerHeader As Global.Comunita_OnLine.UC_ModalPlayerHeader

    '''<summary>
    '''DVtopMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVtopMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTowner_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTowner_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBowner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBowner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTsubmitterType_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmitterType_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBsubmitterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmitterType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTsubmissionStatus_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmissionStatus_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBsubmissionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmissionStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LIsubmissionInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIsubmissionInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTsubmittedOn_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmittedOn_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBsubmittedOnData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmittedOnData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBsubmittedOnTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmittedOnTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SPNsubmittedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPNsubmittedBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTsubmittedBy_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTsubmittedBy_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBsubmittedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBsubmittedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LIrevisions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIrevisions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LTrevisionListTitle_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionListTitle_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DDLrevisions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLrevisions As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HYPlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPlist As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HYPsubmissionsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HYPsubmissionsList As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''CTRLreport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRLreport As Global.Comunita_OnLine.UC_SubmissionExport

    '''<summary>
    '''SPNmanage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPNmanage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BTNaccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNaccept As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNrefuse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNrefuse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNsubmitForUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNsubmitForUser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNreview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVrevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVrevision As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DVdeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVdeadline As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBdeadline_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdeadline_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RDPdeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDPdeadline As Global.Telerik.Web.UI.RadDateTimePicker

    '''<summary>
    '''LBrequestReason_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrequestReason_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TXBreason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXBreason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBreasonHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBreasonHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTmaxCharsrequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTmaxCharsrequest As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BTNaddRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNaddRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNundoRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNundoRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DVmessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DVmessages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MLVpendingMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVpendingMessage As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWpendingEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWpendingEmpty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''VIWpendingUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWpendingUser As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBrequiredRevision_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrequiredRevision_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HTPreviewUserSubmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HTPreviewUserSubmission As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HTPviewUserRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HTPviewUserRequest As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BTNcancelUserRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcancelUserRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNrefuseUserRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNrefuseUserRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNacceptUserRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNacceptUserRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VIWpendingManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWpendingManager As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LTrevisionRequired_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionRequired_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTrevisionRequiredBy_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionRequiredBy_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBrevisionRequiredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrevisionRequiredBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBrevisionMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrevisionMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTdeadline_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTdeadline_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBdeadlineDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBdeadlineDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HTPreviewManagerSubmission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HTPreviewManagerSubmission As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BTNcancelManagerReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNcancelManagerReview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MLVrevisionInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVrevisionInfo As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWinfoEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWinfoEmpty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''VIWinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWinfo As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LTrevisionRequiredInfo_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionRequiredInfo_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTrevisionRequiredByInfo_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionRequiredByInfo_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBrevisionRequiredByInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrevisionRequiredByInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBrevisionMessageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrevisionMessageInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTrevisionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LTrevisionManagedByInfo_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionManagedByInfo_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBrevisionManagedByInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrevisionManagedByInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTrevisionDate_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTrevisionDate_t As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBrevisionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBrevisionDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MLVpreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MLVpreview As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VIWempty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWempty As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''LBemptyMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBemptyMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VIWcall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIWcall As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''FLDcallInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FLDcallInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBcallDescriptionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBcallDescriptionTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LTcallDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTcallDescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LBtimeValidity_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBtimeValidity_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBstartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBstartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBendDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBendDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBwinnerinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBwinnerinfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RPTattachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTattachments As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RPTsections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTsections As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''RPTrequiredFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTrequiredFiles As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''HDNdownloadTokenValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNdownloadTokenValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Comunita_OnLine.AjaxPortal
        Get
            Return CType(MyBase.Master, Comunita_OnLine.AjaxPortal)
        End Get
    End Property
End Class
