//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using lm.Comol.Modules.TaskList.Domain;
using System.Web;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 




namespace lm.Comol.Modules.TaskList.Domain
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
 //   [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]

public partial class ProjectForGanttXML {
    
    private List<TaskForGanttXML> itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("task", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<TaskForGanttXML> Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    public ProjectForGanttXML()
    {
        itemsField = new List<TaskForGanttXML>();
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TaskForGanttXML {
    
    private string pIDField;
    
    private string pNameField;
    
    private string pStartField;
    
    private string pEndField;
    
    private string pColorField;
    
    private string pLinkField;
    
    private string pMileField;
    
    private string pResField;
    
    private string pCompField;
    
    private string pGroupField;
    
    private string pParentField;
    
    private string pOpenField;
    
    private string pDependField;
    
    private string pCaptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pID {
        get {
            return this.pIDField;
        }
        set {
            this.pIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pName {
        get {
            return System.Web.HttpUtility.HtmlEncode(this.pNameField);
        }
        set {
            System.Web.HttpUtility.HtmlEncode(this.pNameField = value);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pStart {
        get {
            return this.pStartField;
        }
        set {
            this.pStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pEnd {
        get {
            return this.pEndField;
        }
        set {
            this.pEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pColor {
        get {
            return this.pColorField;
        }
        set {
            this.pColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pLink {
        get {
            return this.pLinkField;
        }
        set {
            this.pLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pMile {
        get {
            return this.pMileField;
        }
        set {
            this.pMileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pRes {
        get {
            return this.pResField;
        }
        set {
            this.pResField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pComp {
        get {
            return this.pCompField;
        }
        set {
            this.pCompField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pGroup {
        get {
            return this.pGroupField;
        }
        set {
            this.pGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pParent {
        get {
            return this.pParentField;
        }
        set {
            this.pParentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pOpen {
        get {
            return this.pOpenField;
        }
        set {
            this.pOpenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pDepend {
        get {
            return this.pDependField;
        }
        set {
            this.pDependField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pCaption {
        get {
            return this.pCaptionField;
        }
        set {
            this.pCaptionField = value;
        }
    }


    public TaskForGanttXML(Task oTask,bool isLeaf,string BaseUrl)
    {
        pID = oTask.ID.ToString();
        if (oTask.Level == 0)
        {
            pName = oTask.Name;
            pParent = "0";
        }
        else
        {
            string FinalWBS = "";
            string s = oTask.WBS;
            string[] words = s.Split('.');
            //foreach (string w in words) 
            for (int i = 0; i < words.Length; i++)
            {
                if (words[i].Length == 1)
                {
                    FinalWBS += "0" + words[i];
                }
                else
                {
                    FinalWBS += words[i];
                }

                if (i !=words.Length-1)
                {
                    FinalWBS +=  ".";
                }           

            }
            pName = FinalWBS + " " + oTask.Name;
            pParent = oTask.TaskParent.ID.ToString();

        }
       
        pStart = oTask.StartDate.ToString();
        pEnd = oTask.EndDate.ToString();
        if (oTask.Completeness == 0)
        {
            pComp = "0";
            pColor = "ff4070";
        }
        else if (oTask.Completeness == 100)
        {
            pColor = "00e100";
            pComp = oTask.Completeness.ToString();
        }
        else
        {
            pColor = "ffff80";
            pComp = oTask.Completeness.ToString();
        }
        if (isLeaf) 
        {
            pGroup="0";
        }
        else
        {
        pGroup="1";
        }

        pLink = BaseUrl + "TaskList/TaskDetail.aspx?CurrentTaskID=" + oTask.ID + "&CurrentViewType=Read";
    }
    public TaskForGanttXML()
    { }

}

}