'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SRV_accessMonitor
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dtoDate", [Namespace]:="http://schemas.datacontract.org/2004/07/lm.WS.ActionStatistics.Domain"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dtoDate
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private DayField As Integer
        
        Private HourField As Integer
        
        Private MonthField As Integer
        
        Private YearField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Day() As Integer
            Get
                Return Me.DayField
            End Get
            Set
                If (Me.DayField.Equals(value) <> true) Then
                    Me.DayField = value
                    Me.RaisePropertyChanged("Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Hour() As Integer
            Get
                Return Me.HourField
            End Get
            Set
                If (Me.HourField.Equals(value) <> true) Then
                    Me.HourField = value
                    Me.RaisePropertyChanged("Hour")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Month() As Integer
            Get
                Return Me.MonthField
            End Get
            Set
                If (Me.MonthField.Equals(value) <> true) Then
                    Me.MonthField = value
                    Me.RaisePropertyChanged("Month")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Year() As Integer
            Get
                Return Me.YearField
            End Get
            Set
                If (Me.YearField.Equals(value) <> true) Then
                    Me.YearField = value
                    Me.RaisePropertyChanged("Year")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AccessResult", [Namespace]:="http://schemas.datacontract.org/2004/07/lm.WS.UserAccessMonitor.DataContracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AccessResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommunityIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DayField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HourField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PersonIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsageTimeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CommunityID() As Integer
            Get
                Return Me.CommunityIDField
            End Get
            Set
                If (Me.CommunityIDField.Equals(value) <> true) Then
                    Me.CommunityIDField = value
                    Me.RaisePropertyChanged("CommunityID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Day() As Date
            Get
                Return Me.DayField
            End Get
            Set
                If (Me.DayField.Equals(value) <> true) Then
                    Me.DayField = value
                    Me.RaisePropertyChanged("Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Hour() As Integer
            Get
                Return Me.HourField
            End Get
            Set
                If (Me.HourField.Equals(value) <> true) Then
                    Me.HourField = value
                    Me.RaisePropertyChanged("Hour")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PersonID() As Integer
            Get
                Return Me.PersonIDField
            End Get
            Set
                If (Me.PersonIDField.Equals(value) <> true) Then
                    Me.PersonIDField = value
                    Me.RaisePropertyChanged("PersonID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsageTime() As Integer
            Get
                Return Me.UsageTimeField
            End Get
            Set
                If (Me.UsageTimeField.Equals(value) <> true) Then
                    Me.UsageTimeField = value
                    Me.RaisePropertyChanged("UsageTime")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserWithResult", [Namespace]:="http://schemas.datacontract.org/2004/07/lm.WS.UserAccessMonitor.DataContracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserWithResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommunityIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PersonIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CommunityID() As Integer
            Get
                Return Me.CommunityIDField
            End Get
            Set
                If (Me.CommunityIDField.Equals(value) <> true) Then
                    Me.CommunityIDField = value
                    Me.RaisePropertyChanged("CommunityID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PersonID() As Integer
            Get
                Return Me.PersonIDField
            End Get
            Set
                If (Me.PersonIDField.Equals(value) <> true) Then
                    Me.PersonIDField = value
                    Me.RaisePropertyChanged("PersonID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Result() As Integer
            Get
                Return Me.ResultField
            End Get
            Set
                If (Me.ResultField.Equals(value) <> true) Then
                    Me.ResultField = value
                    Me.RaisePropertyChanged("Result")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SRV_accessMonitor.IServiceUserAccessMonitor")>  _
    Public Interface IServiceUserAccessMonitor
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityAccess", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityAccessResponse")>  _
        Function GetCommunityAccess(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonID As Integer, ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalAccess", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalAccessResponse")>  _
        Function GetPortalAccess(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityUserAccessResult", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityUserAccessResultResponse"& _ 
            "")>  _
        Function GetCommunityUserAccessResult(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonsID As System.Collections.Generic.List(Of Integer), ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalUserAccessResult", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalUserAccessResultResponse")>  _
        Function GetPortalUserAccessResult(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonsID As System.Collections.Generic.List(Of Integer)) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/FindCommunitiesWithAccessResult", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/FindCommunitiesWithAccessResultRespo"& _ 
            "nse")>  _
        Function FindCommunitiesWithAccessResult(ByVal PersonD As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/FindPortalUsersWithAccessResult", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/FindPortalUsersWithAccessResultRespo"& _ 
            "nse")>  _
        Function FindPortalUsersWithAccessResult() As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/FindUsersWithAccessResult", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/FindUsersWithAccessResultResponse")>  _
        Function FindUsersWithAccessResult(ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityUsersAccessResultBetween"& _ 
            "Date", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityUsersAccessResultBetween"& _ 
            "DateResponse")>  _
        Function GetCommunityUsersAccessResultBetweenDate(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalUsersAccessResultBetweenDat"& _ 
            "e", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalUsersAccessResultBetweenDat"& _ 
            "eResponse")>  _
        Function GetPortalUsersAccessResultBetweenDate(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityAccessResultBetweenDate", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetCommunityAccessResultBetweenDateR"& _ 
            "esponse")>  _
        Function GetCommunityAccessResultBetweenDate(ByVal PersonIDList As System.Collections.Generic.List(Of Integer), ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalAccessResultBetweenDate", ReplyAction:="http://tempuri.org/IServiceUserAccessMonitor/GetPortalAccessResultBetweenDateResp"& _ 
            "onse")>  _
        Function GetPortalAccessResultBetweenDate(ByVal PersonIDList As System.Collections.Generic.List(Of Integer), ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceUserAccessMonitorChannel
        Inherits SRV_accessMonitor.IServiceUserAccessMonitor, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceUserAccessMonitorClient
        Inherits System.ServiceModel.ClientBase(Of SRV_accessMonitor.IServiceUserAccessMonitor)
        Implements SRV_accessMonitor.IServiceUserAccessMonitor
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetCommunityAccess(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonID As Integer, ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetCommunityAccess
            Return MyBase.Channel.GetCommunityAccess(FromDate, ToDate, PersonID, CommunityID)
        End Function
        
        Public Function GetPortalAccess(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetPortalAccess
            Return MyBase.Channel.GetPortalAccess(FromDate, ToDate, PersonID)
        End Function
        
        Public Function GetCommunityUserAccessResult(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonsID As System.Collections.Generic.List(Of Integer), ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetCommunityUserAccessResult
            Return MyBase.Channel.GetCommunityUserAccessResult(FromDate, ToDate, PersonsID, CommunityID)
        End Function
        
        Public Function GetPortalUserAccessResult(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal PersonsID As System.Collections.Generic.List(Of Integer)) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetPortalUserAccessResult
            Return MyBase.Channel.GetPortalUserAccessResult(FromDate, ToDate, PersonsID)
        End Function
        
        Public Function FindCommunitiesWithAccessResult(ByVal PersonD As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.FindCommunitiesWithAccessResult
            Return MyBase.Channel.FindCommunitiesWithAccessResult(PersonD)
        End Function
        
        Public Function FindPortalUsersWithAccessResult() As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.FindPortalUsersWithAccessResult
            Return MyBase.Channel.FindPortalUsersWithAccessResult
        End Function
        
        Public Function FindUsersWithAccessResult(ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.UserWithResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.FindUsersWithAccessResult
            Return MyBase.Channel.FindUsersWithAccessResult(CommunityID)
        End Function
        
        Public Function GetCommunityUsersAccessResultBetweenDate(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetCommunityUsersAccessResultBetweenDate
            Return MyBase.Channel.GetCommunityUsersAccessResultBetweenDate(FromDate, ToDate, CommunityID)
        End Function
        
        Public Function GetPortalUsersAccessResultBetweenDate(ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetPortalUsersAccessResultBetweenDate
            Return MyBase.Channel.GetPortalUsersAccessResultBetweenDate(FromDate, ToDate)
        End Function
        
        Public Function GetCommunityAccessResultBetweenDate(ByVal PersonIDList As System.Collections.Generic.List(Of Integer), ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate, ByVal CommunityID As Integer) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetCommunityAccessResultBetweenDate
            Return MyBase.Channel.GetCommunityAccessResultBetweenDate(PersonIDList, FromDate, ToDate, CommunityID)
        End Function
        
        Public Function GetPortalAccessResultBetweenDate(ByVal PersonIDList As System.Collections.Generic.List(Of Integer), ByVal FromDate As SRV_accessMonitor.dtoDate, ByVal ToDate As SRV_accessMonitor.dtoDate) As System.Collections.Generic.List(Of SRV_accessMonitor.AccessResult) Implements SRV_accessMonitor.IServiceUserAccessMonitor.GetPortalAccessResultBetweenDate
            Return MyBase.Channel.GetPortalAccessResultBetweenDate(PersonIDList, FromDate, ToDate)
        End Function
    End Class
End Namespace
